version: '3'
services:
  web:
    image: webdevops/php-apache:alpine-php7
    container_name: apache_server
    ports:
      - "4500:80"
    volumes:
      - /home/r1/docker-projeto1-apache-dio/data/html/:/app
    networks:
      - minha-rede

  db:
    image: mysql:5.7
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: "Senha123"
      MYSQL_DATABASE: "testedb"
    ports:
      - "3306:3306"
    volumes:
      - /home/r1/docker-projeto1-apache-dio/data/mysql/:/var/lib/mysql
    networks:
      - minha-rede

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_server
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "Senha123"
    ports:
      - "8000:80"
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge
